### ISSUE TITLE
Broken gtk look

### ISSUE THREAD

**Issue by GoogleCodeExporter** [belangeo/soundgrain#15]
```
What steps will reproduce the problem?
Just try it with qtcurve-gtk and dark color scheme (for sharp effect)

What is the expected output? What do you see instead?
With dark theme background have same color, as without any theme at all (empty 
GTK2_RC_FILES variable).

What version of the product are you using? On what operating system?
Ubuntu 12.04
wxgtk 2.8.21.1

Please provide any additional information below.
It could be wx bug, however on screenshots, provided on wxpython site, all 
looks well (though  did not see dark gtk examples, only clearlooks-based one).
And audacity, another known using wxgtk, doesn't have such problem.
```

Original issue reported on code.google.com by `nick877...@gmail.com` on 2 Apr 2013 at 9:09

**Comment by freemanfromgodotengine** [comment]
I can confirm, that text is unreadable when some variants of "dark" themes are used.
![screenshot_2018-02-10_03-48-15](https://user-images.githubusercontent.com/11817561/36058078-db3668a2-0e18-11e8-8f79-e1f688ff2504.png)


In my case it's XFCE4 and "Vertex-Maia-Dark" and "Breath-Dark" on  Manjaro Linux.
"Adwaita-dark" works a little better. Text is quite readable, but will strain your eyes.
I can also confirm, that Audacity does not have similar problem and looks like this with the same theme: ![screenshot_2018-02-10_04-05-59](https://user-images.githubusercontent.com/11817561/36058081-ed21c4e4-0e18-11e8-98dd-d6715abeaae9.png)
