### ISSUE TITLE
Soundgrain doesn't let me open soundfiles (windows)

### ISSUE THREAD

**Issue by xbladedancer** [belangeo/soundgrain#19]
# So I press open soundfile, select my sample (bear in mind it is a file supported by soundgrain) and then double click on it. It then does nothing except say "audio drivers loaded" in the bottom left corner.

Any help would be greatly appreciated, thank you.

UPDATE: Attached is a screenshot of the dialogue window
![capture](https://cloud.githubusercontent.com/assets/18730592/14907171/271d740c-0d82-11e6-8277-7d475a455517.PNG)

**Comment by laundmo** [comment]
same error here.

windows 10 
soundgrain 6.0.1

**Comment by belangeo** [comment]
Yep!
