### ISSUE TITLE
changed audio settings - now won't open

### ISSUE THREAD

**Issue by ZestieBumwhig** [belangeo/soundgrain#20]
using SoundGrain 4.1 on Ubuntu 14.04... had been successful/great, but then I tried different audio output settings. Changed to 64-bit, restarted as directed, now it won't open b/c the settings are bad. Is there a way to open in "safe" mode?

Cecilia still works fine...
Thanks for your great software, by the way! I love both these programs.

`pyo version 0.6.8 (uses double precision)`

`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe`
`ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side`
`ALSA lib pcm_dmix.c:961:(snd_pcm_dmix_open) The dmix plugin supports only playback stream`
`ALSA lib pcm_dsnoop.c:557:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream`
`ALSA lib pcm_dsnoop.c:557:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream`
`portaudio error in Pa_OpenStream: Invalid sample rate`
`Portaudio error: Invalid sample rate`
`Server not booted.`
`Traceback (most recent call last):`
`  File "/usr/bin/soundgrain", line 2487, in <module>`
`    app = SoundGrainApp()`
`  File "/usr/bin/soundgrain", line 2476, in __init__`
`    self.frame = MainFrame(None, -1, pos=(20,20), size=(sizex,sizey))`
`  File "/usr/bin/soundgrain", line 1879, in __init__`
`    self.check(auDriver)`
`  File "/usr/bin/soundgrain", line 1917, in check`
`    self.controls.bootServer()`
`  File "/usr/bin/soundgrain", line 1475, in bootServer`
`    self.parent.sg_audio.boot(self.parent.audioDriver, self.nchnls, self.samplingRate, self.midiInterface)`
`  File "/usr/lib/python2.7/dist-packages/soundgrain/Resources/audio.py", line 202, in boot`
`    self.mixer = Mixer(outs=10, chnls=chnls)`
`  File "/usr/lib/python2.7/dist-packages/pyolib/pan.py", line 577, in __init__`
`    PyoObject.__init__(self, mul, add)`
`  File "/usr/lib/python2.7/dist-packages/pyolib/_core.py", line 376, in __init__`
`    PyoObjectBase.__init__(self)`
`  File "/usr/lib/python2.7/dist-packages/pyolib/_core.py", line 262, in __init__`
`    raise PyoServerStateException("The Server must be booted before creating any audio object.")`
`pyolib._core.PyoServerStateException: The Server must be booted before creating any audio object.`

**Comment by belangeo** [comment]
Closing the issue since deleting the preferences resolve the problem.
