### ISSUE TITLE
add midi input

### ISSUE THREAD

**Issue by Reaper10** [belangeo/soundgrain#21]
could you add midi input to play the sound by keyboard?

**Comment by belangeo** [comment]
It's already there! See "Midi Settings..." in the Midi menu to configure. In the documentation (link in the Help menu), there is a section about how to use MIDI to control Soundgrain.

**Comment by Reaper10** [comment]
oh okay you ever thought making an lv2

**Comment by belangeo** [comment]
Nope, Soundgrain is a standalone, and will probably never be a plugin...
